=== valentin-kudin/mailru-test-automation-framework/src/main/resources/xml/users.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="status" type="xs:string"/>
                            <xs:element name="login" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== valentin-kudin/mailru-test-automation-framework/src/main/resources/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="users.xsd">
    <User id="1">
        <status>valid</status>
        <login>testwoods</login>
        <password>q7(gJ6LN%-6k***</password>
    </User>
    <User id="2">
        <status>invalid</status>
        <login>parampampam</login>
        <password>sol34554bdfdfj</password>
    </User>
</Users>
